version: "2"

services:
  app:
    build: .
    ports:
      - "8080:3001"
    depends_on:
      - db
    links:
      - db
    networks:
      - jottNetwork

  db:
    image: mysql:8.0.3
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jott
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - jottNetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - jottNetwork

volumes:
  my-datavolume:

networks:
   jottNetwork:
     driver: "bridge"